language: java
env: MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=192m" GRADLE_OPTS="-Xmx1024m -XX:MaxPermSize=192m"
  TERM="dumb"
jdk:
- oraclejdk8
sudo: required
services:
- docker
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y xmlstarlet jq
- sudo chsh --shell $(which bash)
install: true
before_script:
- export -f travis_nanoseconds
- export -f travis_fold
- export -f travis_time_start
- export -f travis_time_finish
script:
- set -o errexit
- source travis-helpers.sh
- script_block 'gradle-build' './gradlew clean && ./gradlew build'
- script_block 'groovy-test' 'groovy testbuild.groovy -gradle'
- script_block 'make' 'make TAG=SNAPSHOT BUILD_NUM=$TRAVIS_BUILD_NUMBER rpm deb'
- script_block 'deb-test' 'bash test-docker-install-deb.sh'
- script_block 'rpm-test' 'bash test-docker-install-rpm.sh'
- script_block 'api-test' 'DOCKER_COMPOSE_SPEC=docker-compose-api-mysql.yaml bash run-docker-api-tests.sh'
- script_block 'docker-test' 'bash run-docker-tests.sh'
- script_block 'docker-ssl-test' 'bash run-docker-ssl-tests.sh'
- script_block 'docker-ansible-test' 'bash run-docker-ansible-tests.sh'
addons:
  hostname: rdbuild
  apt:
    packages:
    - groovy
    - rpm
    - make
    - zip
    - unzip
    - fakeroot
branches:
  only:
    - master
    - release-2.11
    - prerelease-2.12.0

notifications:
  irc:
  - irc.freenode.org#rundeck
  slack:
    secure: ep3APeVD6QwEkTJ8YR0f1eDzcFJ2uLUIci4Aob/5ILm+v8h0hOTAe1yFoKv+iR/4PCeZ+5PvVezOMHSkFNX7rCj06Mj/ivlnng569JLjOQAR0q25aeIH+wy4oDE33HaNbNOYLMe7bXDP4SelRi9SbRRe84j6OjDgZzyDC36cyAk=
